version: '2'
services:

  jenkins:
    image: stephenreed/jenkins-java8-maven-git
    ports:
      - "7001:8080"
      - "9999:9999"
    networks:
      - front-tier
      - back-tier


networks:
  front-tier:
  back-tier:


#docker kill $(docker ps -q)
#8080:8081 - 8080 is expose to external , 8081 is internal
#docker-compose up --force-recreate
